/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
import type * as nftSol from "./NFT.sol";
export type { nftSol };
import type * as test from "./test";
export type { test };
export type { NFTFactory } from "./NFTFactory";
