/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface NFTFactoryInterface extends utils.Interface {
  functions: {
    "createNFTCollection(string,string,uint256,address)": FunctionFragment;
    "getOwnCollections()": FunctionFragment;
    "isNFT(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createNFTCollection"
      | "getOwnCollections"
      | "isNFT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createNFTCollection",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnCollections",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isNFT",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createNFTCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isNFT", data: BytesLike): Result;

  events: {
    "CreatedNFTCollection(address,address,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatedNFTCollection"): EventFragment;
}

export interface CreatedNFTCollectionEventObject {
  creator: string;
  nft: string;
  name: string;
  symbol: string;
}
export type CreatedNFTCollectionEvent = TypedEvent<
  [string, string, string, string],
  CreatedNFTCollectionEventObject
>;

export type CreatedNFTCollectionEventFilter =
  TypedEventFilter<CreatedNFTCollectionEvent>;

export interface NFTFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NFTFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createNFTCollection(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _royaltyFee: PromiseOrValue<BigNumberish>,
      _royaltyRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getOwnCollections(overrides?: CallOverrides): Promise<[string[]]>;

    isNFT(
      _nft: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  createNFTCollection(
    _name: PromiseOrValue<string>,
    _symbol: PromiseOrValue<string>,
    _royaltyFee: PromiseOrValue<BigNumberish>,
    _royaltyRecipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getOwnCollections(overrides?: CallOverrides): Promise<string[]>;

  isNFT(
    _nft: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    createNFTCollection(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _royaltyFee: PromiseOrValue<BigNumberish>,
      _royaltyRecipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getOwnCollections(overrides?: CallOverrides): Promise<string[]>;

    isNFT(
      _nft: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "CreatedNFTCollection(address,address,string,string)"(
      creator?: null,
      nft?: null,
      name?: null,
      symbol?: null
    ): CreatedNFTCollectionEventFilter;
    CreatedNFTCollection(
      creator?: null,
      nft?: null,
      name?: null,
      symbol?: null
    ): CreatedNFTCollectionEventFilter;
  };

  estimateGas: {
    createNFTCollection(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _royaltyFee: PromiseOrValue<BigNumberish>,
      _royaltyRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getOwnCollections(overrides?: CallOverrides): Promise<BigNumber>;

    isNFT(
      _nft: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createNFTCollection(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      _royaltyFee: PromiseOrValue<BigNumberish>,
      _royaltyRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getOwnCollections(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isNFT(
      _nft: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
